### ISSUE TITLE
使用androidx 会报错 v7无问题

### ISSUE THREAD

**Issue by OneTake1998** [JantHsueh/Fragmentation#1]
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mall/com.example.mall.MainActivity}: java.lang.ClassCastException: com.example.mall.MainActivity cannot be cast to me.yokeyword.fragmentation.SupportActivity

**In addition, we do not accept issues unrelated to Fragmentation.**
```

**Comment by JantHsueh** [comment]
如果是使用implements ISupportActivity 的方式，那么需要implements ISupportFragment（而不是extend SupportFragment），并且按需要复写onAttach 方法，如下，注意_mActivity的类型

```
   protected FragmentActivity _mActivity;

      @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        mDelegate.onAttach();
        _mActivity = mDelegate.getActivity();
    }

```

**Comment by Sevencats** [comment]
我也遇到了同样的问题，请问你解决了吗？在androidx的包下

**Comment by jueduiyheng** [comment]
> 如果是使用implements ISupportActivity 的方式，那么需要implements ISupportFragment（而不是extend SupportFragment），并且按需要复写onAttach 方法，如下，注意_mActivity的类型
> 
> ```
>    protected FragmentActivity _mActivity;
> 
>       @Override
>     public void onAttach(Context context) {
>         super.onAttach(context);
>         mDelegate.onAttach();
>         _mActivity = mDelegate.getActivity();
>     }
> ```

搞定, 自动导包惹的祸
