### ISSUE TITLE
java.lang.IllegalAccessError: Field 'androidx.fragment.app.FragmentManager.mStateSaved' is inaccessible to class 'androidx.fragment.app.FragmentationMagician'

### ISSUE THREAD

**Issue by demoface** [JantHsueh/Fragmentation#12]
android 10 
java.lang.IllegalAccessError: Field 'androidx.fragment.app.FragmentManager.mStateSaved' is inaccessible to class 'androidx.fragment.app.FragmentationMagician'

**Comment by JantHsueh** [comment]
fragmentation version update to 1.0.6
