### ISSUE TITLE
android.support 无法拉取库

### ISSUE THREAD

**Issue by ruanbaojun1105** [JantHsueh/Fragmentation#16]
api 'me.xuexuan:fragmentation:1.0.6'
    api 'me.xuexuan:fragmentation-swipeback:1.0.6'

无法下载

**Comment by JantHsueh** [comment]
该库现在使用的都是androix系列的，为了区分，使用 'me.xuexuan:fragmentationx:1.0.6'

**Comment by ruanbaojun1105** [comment]
都还有很多项目没换到X，哎！ @JantHsueh
