### ISSUE TITLE
使用ViewPager承载Fragment时会因offscreenPageLimit缓存设置而无法调用supportVisible函数

### ISSUE THREAD

**Issue by Ubitar** [JantHsueh/Fragmentation#3]
很高兴大佬接手这项目。
我遇到了下面的问题：

A Activity页面有ViewPager+4个fragment
B Activity页面只有一个按钮

先打开A再打开B页面，点击按钮，通过类似EventBus这一类总线告知A页面，切换Viewpager的位置，然后点击返回A页面，发现切换后新的fragment页面是没有调用到supportVisible函数的，onLazyLoad更没有。

在多此尝试后，发现这是跟fragment是否在offscreenPageLimit缓存范围内有关的，如果在缓存范围外，切换Viewpager后可以调用到supportVisible函数，在缓存范围内就不能调用到。

目前我是自己重写setUserVisibleHint等来实现切换监听的，不知道我这样使用fragmentation对不对

**Comment by Ubitar** [comment]
公司项目限制了只能用activity，不能单activity+多fragment很尴尬

**Comment by JantHsueh** [comment]
在你的项目中，在A Activity 中手动去切换不同的fragment，supportVisible 是否受offscreenPageLimit缓存范围的影响？

**Comment by Ubitar** [comment]
A  Activity下方是有4个Tab的，点击tab或者手动左右滑动，viewPager随意从索引0切换至1或者23都能触发supportVisible函数，不受offscreenPageLimit大小的影响，包括通过EventBus也可以切换。
但只要A Activity被Pause后，再切换viewpager就会出现这问题。
是库中有记录过fragment状态导致的吗

**Comment by Ubitar** [comment]
好吧，自己重新测试了下，单Activity-多Fragment就没有这种情况，看来是不应该多Activity-多Activity这样玩
