### ISSUE TITLE
Method 'boolean androidx.fragment.app.Fragment.isInBackStack()' is inaccessible to class 'androidx.core.app.BackstackAccessor' (declaration of 'androidx.core.app.BackstackAccessor' appears in /data/app/com.nj.doc-2/base.apk)

### ISSUE THREAD

**Issue by gsn516** [JantHsueh/Fragmentation#4]
# Issues Guideline

Following information can help us to resolve the issue faster.

* Library version
* Support-v4 version
* Logs
* Screenshots

**In addition, we do not accept issues unrelated to Fragmentation.**

**Comment by gsn516** [comment]
这是跳转到一个activity，这个activity里加载的一个fragment**A**，loadRootFragment(R.id.fl_container, MyMedicineBoxForSelect.newInstance());然后这个MyMedicineBoxForSelect里的一个按钮点击进入一个新的fragment**B**（start(DrugLibListFragmentForSelect.newInstance());）是个时候，**B**点击返回就报上面的错了

**Comment by JantHsueh** [comment]
提供一下这些信息
1、fragmentation 的版本号
2、检查项目中最新的androidx.fragment 的版本号（可参考，我之前写的[这篇文章](https://blog.csdn.net/xx326664162/article/details/71488551)）

**Comment by gsn516** [comment]
> 提供一下这些信息
> 1、fragmentation 的版本号
> 2、检查项目中最新的androidx.fragment 的版本号（可参考，我之前写的[这篇文章](https://blog.csdn.net/xx326664162/article/details/71488551)）

已经解决，遇到同样问题的可参考https://github.com/sockeqwe/mosby/issues/318
