### ISSUE TITLE
compilesdk升级到29

### ISSUE THREAD

**Issue by tadpole145** [JantHsueh/Fragmentation#8]
# 解决sdk升级29的问题.
* Library version :29

**我用这个库半年了,看到作者停止维护,就想拉下来,自己维护,在原作者issues中看到你在接任维护,我想把sdk升级到29,发现报错了,FragmentManagerImpl这个类非public,原作者写的FragmentationMagician无法访问FragmentManagerImpl,于是乎去找答案,没找到,自己折腾了一上午,终于搞定了,就是把AndroidX中FragmentManagerImpl源代码完全复制一份,新建一个一模一样的包名,效果如下图所示.最后能正常跑起来,暂时没发现什么bug..大佬既然有心维护,能不能建个群一起交流讨论,这个库真心挺好用的. 上个issure中的setMaxLifeCycle,是新api,getUserVisibleHint确实已经废弃了,那么FragmentManagerImpl可以自己复制,是不是可以想想办法,应用到setMaxLifeCycle呢?
![未命名1589263307](https://user-images.githubusercontent.com/35562133/81643880-29a68300-9459-11ea-8500-42d7f9f11985.png)
**

**Comment by JantHsueh** [comment]
最近是在兼容sdk 29，直接复制FragmentManagerImpl的方法，只对29有效，其他的sdk版本可能会出问题。setMaxLifeCycle 后续也会跟进。

**Comment by JantHsueh** [comment]
1、关于fragment 变量访问不到的问题，已经在计划中。 

2、如果你使用的是 androidx ，升级sdk 是没有问题的。如果你使用sdk ，应该复制android.app.Fragment ，而不是 androidx.fragment:fragment 里的该文件，否则容易出问题。这样复制可能不兼容其他版本的sdk

3、setMaxLifeCycle 会尽快应用

**Comment by tadpole145** [comment]
android.app.Fragment已经被标记为废弃了哦..估计google以后推的都是androidx的包吧.
